services:
  - type: web
    name: medscoop
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: orders.db
